POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer 

{
      "title": "Auto add to user10",
      "author": "Fullstackopen",
      "url": "https://fullstackopen.com",
      "likes": 100
}