POST http://localhost:3001/api/users
Content-Type: application/json

{
      "username": "Testi Mies5",
      "name": "Testman 2",
      "password": "salainen",
      "blogs": "637ba8e376d13f755c65ac2c"
}